name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run CI Script
        run: yarn ci
